#pragma once

typedef enum {
	StrID_NONE,
	StrID_Name,
	StrID_Description,
	StrID_Banner_Param_Name,
	StrID_Preset,
	StrID_Preset_Choices,
	StrID_Display_Group,
	StrID_Display_Mode,
	StrID_Display_Mode_Choices,
	StrID_Gamma_Correction,
	StrID_Depth_Group,
	StrID_Depth_Layer,
	StrID_Depth_Channel,
	StrID_Depth_Channel_Choices,
	StrID_Depth_Invert,
	StrID_Depth_Focus,
	StrID_Depth_SetFocus,
	StrID_Depth_Curve,
	StrID_Depth_NearBlur,
	StrID_Depth_Blackpoint,
	StrID_Depth_Whitepoint,
	StrID_Depth_ForegroundProtect,
	StrID_Aperture_Group,
	StrID_Aperture_Shape,
	StrID_Aperture_Shape_Choices,
	StrID_Custom_Aperture,
	StrID_Aspect_Ratio,
	StrID_Aperture_Size,
	StrID_Sample_Count,
	StrID_Barrel_Distortion,
	StrID_Softness,
	StrID_Aperture_Blades,
	StrID_Blade_Angle,
	StrID_Blade_Curve,
	StrID_Notch_Angle,
	StrID_Notch_Scale,
	StrID_LensCharacter_Group,
	StrID_Spherical_Aberration,
	StrID_Spherical_Aberration_Plus,
	StrID_Spherical_Aberration_Scale,
	StrID_Spherical_Aberration_Offset,
	StrID_Optical_Vignetting,
	StrID_Optical_Vignetting_Scale,
	StrID_Astigmatism,
	StrID_Catadioptric,
	StrID_Catadioptric_Scale,
	StrID_CA_Group,
	StrID_Highlights_Group,
	StrID_Highlights_Lower,
	StrID_Highlights_Upper,
	StrID_Highlights_Softness,
	StrID_Highlights_Saturation,
	StrID_Highlights_Enhancement,
	StrID_Highlights_BokehGamma,
	StrID_Highlights_Scatter,
	StrID_Highlights_Recovery,
	StrID_Highlights_Tint,
	StrID_ApTex_Group,
	StrID_ApTex_Layer,
	StrID_ApTex_Invert,
	StrID_ApTex_Intensity,
	StrID_ApTex_Scale,
	StrID_ApTex_Offset,
	StrID_MatteBox_Group,
	StrID_MatteBox_Top,
	StrID_MatteBox_Bottom,
	StrID_MatteBox_Left,
	StrID_MatteBox_Right,
	StrID_Noise_Group,
	StrID_Noise_Amount,
	StrID_Noise_Animated,
	StrID_Noise_Monochromatic,
	StrID_Noise_LumaDistribution,
	StrID_Noise_LumaDistribution_Choices,
	StrID_Noise_MapDistribution,
	StrID_Noise_MapDistribution_Choices,
	StrID_Noise_Tint,
	StrID_About_Title,
	StrID_About_Body,
	// v2.5 (DOF PRO parity)
	StrID_Depth_Gamma,
	StrID_Depth_Smoothing,
	StrID_Aspect_Preset,
	StrID_Aspect_Preset_Choices,
	StrID_Aperture_Map,
	StrID_Aperture_Map_Choices,
	StrID_ApMap_Picker,
	StrID_Bokeh_Preview,
	// v2.7 (Bloom / Halation)
	StrID_Highlights_Bloom,
	StrID_Highlights_BloomRadius,
	StrID_Highlights_BloomThreshold,
	// v2.8 (Render Mode)
	StrID_Render_Mode,
	StrID_Render_Mode_Choices,
	// v2.9 (Procedural Onion Rings)
	StrID_Onion_Rings,
	StrID_Onion_Ring_Count,
	// v2.10 (Field Curvature)
	StrID_Field_Curvature,
	StrID_Field_Sweet,
	// v2.12 (Opponent-axis CA)
	StrID_CA_RedCyan,
	StrID_CA_GreenMagenta,
	StrID_CA_BlueYellow,
	// v2.24 (energy-conserving / sRGB / inpaint)
	StrID_Energy_Conserving,
	StrID_Srgb_Linear,
	StrID_Bg_Inpaint,
	// v2.27 (Depth Levels custom-UI control)
	StrID_Depth_Levels,
	// v2.20/2.21 DoF Mode + Depth Encoding popups and the Physical Lens slider
	// labels were removed in v2.22 (single Aperture-Simple model); see zluxDOF.h.
	StrID_NUMTYPES
} StrIDType;
